### ISSUE TITLE
navbar INPUT menuItem dataProvider

### ISSUE THREAD

**Issue by tgs-1** [Servoy/bootstrapextracomponents#2]
A dataProvider will not bind to an INPUT (INPUT_GROUP) menuItem if the navbar is set by method and the items alignments are different.

**Comment by pruhsert** [comment]
That cannot be fixed currently as it is not implemented in Servoy (see https://support.servoy.com/browse/SVY-10964). Once that is fixed, it should work.

**Comment by tgs-1** [comment]
Hi Patrick,
does this "Fix Version/s: 8.2, 8.1.4" (SVY-10964) mean it will be fixed for that Versions?
It's important for me because of a big design decision.
Thank you, Thomas

**Comment by pruhsert** [comment]
That is what that means, yes.

Can you explain a bit why dynamically setting the dataprovider of a field is so important for you? I can't really understand what the use case is for data bound fields in a menu bar other than a search field maybe.

**Comment by tgs-1** [comment]
Hi Patrick,

indeed it’s a formvariable for a (Google like) search.
If you have an other suggestion for me, you are welcome.

Regards Thomas


On 11. May 2017, at 12:10, Patrick Ruhsert <notifications@github.com> wrote:

That is what that means, yes.

Can you explain a bit why dynamically setting the dataprovider of a field is so important for you? I can't really understand what the use case is for data bound fields in a menu bar other than a search field maybe.

**Comment by pruhsert** [comment]
But why can't you simply create that in designer? The only thing that does not work is the creation via method...

**Comment by tgs-1** [comment]
Because I cannot mix. There are different menuItems depending on the status of the solution.
For example:
MenuItem: Edit -> record can be edited and if I click on it, the menuItem changes to: Lock with subItems: cancel + save


On 11. May 2017, at 17:40, Patrick Ruhsert <notifications@github.com> wrote:

But why can't you simply create that in designer? The only thing that does not work is the creation via method...

**Comment by pruhsert** [comment]
Can't you create the menu with the search box and all other stuff that is fixed and then simply add/remove others?

Just my opinion on this: I find disappearing / reappearing items in a UI always a bit confusing. I prefer that stuff is always there and just the state is toggled. So you have a button "Edit" and "Cancel" / "Save". And I always see all, but there are not always enabled.

**Comment by tgs-1** [comment]
Ok, I will try this, but how can I enable/disable a button/menuItem when I create the navbar by design properties?
Is this possible?

On 11. May 2017, at 17:54, Patrick Ruhsert <notifications@github.com> wrote:

Can't you create the menu with the search box and all other stuff that is fixed and then simply add/remove others?

Just my opinion on this: I find disappearing / reappearing items in a UI always a bit confusing. I prefer that stuff is always there and just the state is toggled. So you have a button "Edit" and "Cancel" / "Save". And I always see all, but there are not always enabled.

**Comment by tgs-1** [comment]
I’m currently testing things around that issue.
For my enable/disable question the answer is onMenuItemClicked, right?

Have a nice weekend
Thomas

On 11. May 2017, at 18:02, yomotec GmbH • Thomas Schnaus <ts@yomotec.de> wrote:

Ok, I will try this, but how can I enable/disable a button/menuItem when I create the navbar by design properties?
Is this possible?

On 11. May 2017, at 17:54, Patrick Ruhsert <notifications@github.com <mailto:notifications@github.com>> wrote:

Can't you create the menu with the search box and all other stuff that is fixed and then simply add/remove others?

Just my opinion on this: I find disappearing / reappearing items in a UI always a bit confusing. I prefer that stuff is always there and just the state is toggled. So you have a button "Edit" and "Cancel" / "Save". And I always see all, but there are not always enabled.

**Comment by pruhsert** [comment]
onWhatever... You should simply try to call

elements.navbar.setMenuItemEnabled(itemId, false);

Let me know if that does what you need

**Comment by tgs-1** [comment]
Hi Patrick,

if I make:

/** @type {Array<bootstrapextracomponents-navbar.menuItem>} */
var menuItems = [
		...
		]


// create navbar1 menuItems
elements.navbar_1.setMenuItems(menuItems);
	
// set menuItems enabled/disabled
elements.navbar_1.setMenuItemEnabled("5", true); // edit == enabled
elements.navbar_1.setMenuItemEnabled("6", false); // cancel == disabled
elements.navbar_1.setMenuItemEnabled("7", false); // save == disabled

I get:

Exception Object: java.lang.NullPointerException
MSG: 
null
 > java.lang.NullPointerException
	at com.servoy.j2db.server.ngclient.component.RhinoMapOrArrayWrapper.has(RhinoMapOrArrayWrapper.java:171)
	at org.mozilla.javascript.ScriptableObject.getBase(ScriptableObject.java:2525)
	at org.mozilla.javascript.ScriptableObject.putProperty(ScriptableObject.java:2321)
	at org.mozilla.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1629)
	at org.mozilla.javascript.ScriptRuntime.setObjectProp(ScriptRuntime.java:1620)
	at org.mozilla.javascript.gen.c_3._c_anonymous_5(Unknown Source)
	at org.mozilla.javascript.gen.c_3.call(Unknown Source)
	at com.servoy.j2db.server.ngclient.component.RuntimeWebComponent$2.call(RuntimeWebComponent.java:270)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1774)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:837)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:158)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:406)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3204)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:156)
	at com.servoy.j2db.scripting.ScriptEngine.executeFunction(ScriptEngine.java:664)
	at com.servoy.j2db.debug.RemoteDebugScriptEngine.executeFunction(RemoteDebugScriptEngine.java:393)
	at com.servoy.j2db.scripting.ScopesScope.executeGlobalFunction(ScopesScope.java:193)
	at com.servoy.j2db.server.ngclient.NGFormManager.makeSolutionSettings(NGFormManager.java:179)
	at com.servoy.j2db.server.ngclient.NGFormManager$1.run(NGFormManager.java:342)
	at com.servoy.j2db.server.ngclient.NGFormManager.propertyChange(NGFormManager.java:347)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at javax.swing.event.SwingPropertyChangeSupport.firePropertyChange(SwingPropertyChangeSupport.java:92)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at com.servoy.j2db.J2DBGlobals.firePropertyChange(J2DBGlobals.java:92)
	at com.servoy.j2db.server.ngclient.NGClient.loadSolution(NGClient.java:609)
	at com.servoy.j2db.ClientState.selectAndOpenSolution(ClientState.java:435)
	at com.servoy.j2db.server.ngclient.NGClient.selectAndOpenSolution(NGClient.java:169)
	at com.servoy.j2db.ClientState.handleClientUserUidChanged(ClientState.java:413)
	at com.servoy.j2db.scripting.ScriptEngine$3.run(ScriptEngine.java:728)
	at org.sablo.eventthread.Event$1.run(Event.java:100)
	at org.sablo.websocket.CurrentWindow.runForWindow(CurrentWindow.java:77)
	at org.sablo.eventthread.Event.execute(Event.java:90)
	at org.sablo.eventthread.EventDispatcher.dispatch(EventDispatcher.java:125)
	at org.sablo.eventthread.EventDispatcher.run(EventDispatcher.java:89)
	at com.servoy.j2db.server.ngclient.eventthread.NGEventDispatcher.run(NGEventDispatcher.java:55)
	at java.lang.Thread.run(Thread.java:748)


I have redesigned my solution, don’t set the INPUT menuItem on the navbar and create the other menuItems still by funtion.
This is more flexibel for me than the static menuItems by design properties.

Regards Thomas

On 12. May 2017, at 18:00, Patrick Ruhsert <notifications@github.com> wrote:

onWhatever... You should simply try to call

elements.navbar.setMenuItemEnabled(itemId, false);

Let me know if that does what you need

**Comment by pruhsert** [comment]
I will look at that after ServoyWorld...

**Comment by pruhsert** [comment]
enabling/disabling issues should be fixed with upcoming 1.1.2
